# Generated by Django 2.2 on 2020-01-17 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
    ]
