# Generated by Django 2.2.2 on 2020-05-29 21:59

import apps.dpv_perfil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_perfil', '0002_auto_20200117_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.dpv_perfil.models.scramble_upload_avatar, verbose_name='Mi Avatar'),
        ),
    ]
