# Generated by Django 2.2.3 on 2021-01-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0003_auto_20190410_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando Respuesta de Técnico', 'ERT'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentcomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Asignación', 'Esperando Asignación'), ('Finalizada', 'Finalizada'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Asignación', 'Esperando Asignación'), ('Finalizada', 'Finalizada'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=200),
        ),
    ]
