# Generated by Django 2.2.3 on 2019-12-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0004_auto_20210105_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('PR', 'Pendiente de Respuesta'), ('PS', 'Pendiente de Solución'), ('ECNS', 'Explicada Causa de no Solución'), ('S', 'Solución o Resuelto'), ('Trámite', 'Trámite')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'EAJ'), ('Pendiente', 'P'), ('Esperando Asignación', 'EA'), ('Esperando Respuesta de Técnico', 'ERT'), ('Finalizada', 'F')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentcomplaint',
            name='current_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Finalizada', 'Finalizada'), ('Esperando Asignación', 'Esperando Asignación')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(blank=True, choices=[('PR', 'Pendiente de Respuesta'), ('PS', 'Pendiente de Solución'), ('ECNS', 'Explicada Causa de no Solución'), ('S', 'Solución o Resuelto'), ('Trámite', 'Trámite')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Finalizada', 'Finalizada'), ('Esperando Asignación', 'Esperando Asignación')], default='Pendiente', max_length=200),
        ),
    ]
