# Generated by Django 2.2.3 on 2019-12-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0005_auto_20191218_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('S', 'Solución o Resuelto'), ('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite'), ('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solución')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando Respuesta de Técnico', 'ERT'), ('Pendiente', 'P'), ('Finalizada', 'F'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Asignación', 'EA')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentcomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Asignación', 'Esperando Asignación'), ('Pendiente', 'Pendiente'), ('Finalizada', 'Finalizada'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(blank=True, choices=[('S', 'Solución o Resuelto'), ('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite'), ('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solución')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Asignación', 'Esperando Asignación'), ('Pendiente', 'Pendiente'), ('Finalizada', 'Finalizada'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe')], default='Pendiente', max_length=200),
        ),
    ]
