# Generated by Django 2.2.3 on 2019-12-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0006_auto_20191218_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('Trámite', 'Trámite'), ('S', 'Solución o Resuelto'), ('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando Asignación', 'EA'), ('Esperando aceptación del jefe', 'EAJ'), ('Finalizada', 'F'), ('Esperando Respuesta de Técnico', 'ERT'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentcomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando Asignación', 'Esperando Asignación'), ('Finalizada', 'Finalizada'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(blank=True, choices=[('Trámite', 'Trámite'), ('S', 'Solución o Resuelto'), ('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando Asignación', 'Esperando Asignación'), ('Finalizada', 'Finalizada'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=200),
        ),
    ]
