# Generated by Django 2.2 on 2020-01-18 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dpv_respuesta', '0002_auto_20200117_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaRechazada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado')),
                ('fecha_rechazada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Rechazo')),
                ('argumento', models.TextField(default='Argumento de rechazo por defecto', verbose_name='Argumento')),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, 'Jefe de Departamento'), (2, 'Director')], default=0)),
                ('rechazador', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Quien Rechaza')),
                ('respuesta', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dpv_respuesta.Respuesta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
