# Generated by Django 2.2.2 on 2020-03-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_respuesta', '0004_auto_20200327_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico', to='dpv_perfil.Perfil'),
        ),
    ]
