# Generated by Django 2.2.2 on 2020-07-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_viviendas', '0003_auto_20200610_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='add_concepto',
            field=models.CharField(blank=True, max_length=500, verbose_name='Datos Concepto'),
        ),
    ]
