# Generated by Django 2.2 on 2020-01-17 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('action_flat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('type_obj_id', models.IntegerField()),
                ('type_obj_name', models.CharField(max_length=100)),
                ('obj_id', models.IntegerField()),
                ('obj_name', models.CharField(max_length=100)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.GenericIPAddressField(default='0.0.0.0')),
                ('medical', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ('action_date', 'action_flat'),
            },
        ),
        migrations.AddField(
            model_name='configmail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configmail',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='configmail',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='filesuploaded',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filesuploaded',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='filesuploaded',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
    ]
