from django.urls import path
from .views import *

urlpatterns = [
   path('', index, name='quejas_list'),
   path('add', agregar_queja, name='quejas_add'),
   path('edit/<int:id_queja>', index, name='quejas_edit'),
   path('del/<int:id_queja>', index, name='quejas_del'),
   path('<int:id_queja>', detalle_queja, name='quejas_detail'),
   path('live/<int:id_queja>', historia_queja, name='quejas_live'),
   path('depto/<int:id_queja>', asignar_queja_depto, name='quejas_asig_depto'),
   path('tecnico/<int:id_queja>', asignar_queja_tecnico, name='quejas_asig_tec'),
   path('tecnico/<int:id_queja>', index, name='quejas_asig_tec'),
   path('response/<int:id_queja>', responder_queja, name='quejas_response'),
   path('jdepto/<int:id_queja>', aprobar_respuesta_tecnico, name='quejas_ajdepto'),
   path('dirtor/<int:id_queja>', aprobar_respuesta_depto, name='quejas_adtor'),
   path('notify/<int:id_queja>', notificar_respuesta_queja, name='quejas_notify'),
   path('depto_many/', index, name='quejas_asig_many_dpto'),
   path('stats/', stats_queja, name='quejas_stats'),
   path('stats/<int:id_municipio>', stats_queja_municipal, name='quejas_stats'),
   # path('stats/<int:id_municipio>/<int:id_cpopular>', stats_queja, name='quejas_stats'),
   path('tecnico_many/', index, name='quejas_asig_many_tec'),
   path('notify_many/', notify_queja, name='quejas_notify_many'),
   path('deny/<int:id_queja>/<int:level>', rechazar_queja, name='quejas_deny'),
   path('redirect/<int:id_queja>', index, name='quejas_redirct'),
   path('damnificados', list_damnificado, name='quejas_damnificados'),
   path('damnificados/json', get_damnificados_json, name='quejas_damn_json'),
   path('damnificados/add', add_damnificado, name='quejas_damnadd'),
   path('damnificados/<int:id_damn>', get_damnificado_detail, name='quejas_damndetail'),
   path('pdf/<int:id_queja>', get_pdf_response, name='quejas_redirct'),
]
