from django.db.models import Q
from .models import *


def create_initial():
    if not Provincia.objects.all().exists():
        Provincia.objects.bulk_create([
            Provincia(numero=1, nombre='Pinar del Rio'),
            Provincia(numero=2, nombre='Artemisa'),
            Provincia(numero=3, nombre='La Habana'),
            Provincia(numero=4, nombre='Mayabeque'),
            Provincia(numero=5, nombre='Matanzas'),
            Provincia(numero=6, nombre='Villa Clara'),
            Provincia(numero=7, nombre='Santi Spiritus'),
            Provincia(numero=8, nombre='Ciego de Avila'),
            Provincia(numero=9, nombre='Camagüey'),
            Provincia(numero=10, nombre='Las Tunas'),
            Provincia(numero=11, nombre='Holguin'),
            Provincia(numero=12, nombre='Gramma'),
            Provincia(numero=13, nombre='Santiago de Cuba'),
            Provincia(numero=14, nombre='Güatánamo'),
            Provincia(numero=15, nombre='Isla de la Juventud'),
        ])

    if not Municipio.objects.all().exists():
        provincia = Provincia.objects.get(nombre='La Habana')
        Municipio.objects.bulk_create([
            Municipio(numero=1, nombre='Playa', provincia=provincia),
            Municipio(numero=2, nombre='Plaza de la Revolución', provincia=provincia),
            Municipio(numero=3, nombre='Habana Vieja', provincia=provincia),
            Municipio(numero=4, nombre='Centro Habana', provincia=provincia),
            Municipio(numero=4, nombre='Cerro', provincia=provincia),
            Municipio(numero=5, nombre='Boyeros', provincia=provincia),
            Municipio(numero=6, nombre='Cotorro', provincia=provincia),
            Municipio(numero=7, nombre='La Lisa', provincia=provincia),
            Municipio(numero=8, nombre='Arroyo Naranjo', provincia=provincia),
            Municipio(numero=9, nombre='Habana del Este', provincia=provincia),
            Municipio(numero=10, nombre='10 de Octubre', provincia=provincia),
            Municipio(numero=11, nombre='San Miguel del Padrón', provincia=provincia),
            Municipio(numero=12, nombre='Marianao', provincia=provincia),
            Municipio(numero=13, nombre='Regla', provincia=provincia),
            Municipio(numero=14, nombre='Güanabacoa', provincia=provincia),
        ])
    else:
        pass

    if not ConsejoPopular.objects.all().exists():
        mun_playa = Municipio.objects.get(nombre='Playa')
        mun_plaza = Municipio.objects.get(nombre='Plaza de la Revolución')
        mun_cerro = Municipio.objects.get(nombre='Cerro')
        mun_ch = Municipio.objects.get(nombre='Centro Habana')

        ConsejoPopular.objects.bulk_create([
            ConsejoPopular(numero=1, nombre='Canal', municipio=mun_cerro),
            ConsejoPopular(numero=2, nombre='Palatino', municipio=mun_cerro),
            ConsejoPopular(numero=3, nombre='Los Sitios', municipio=mun_ch),
            ConsejoPopular(numero=4, nombre='San Leopoldo', municipio=mun_ch),
            ConsejoPopular(numero=5, nombre='Pueblo Nuevo', municipio=mun_ch),
            ConsejoPopular(numero=6, nombre='La Victoria', municipio=mun_ch),
            ConsejoPopular(numero=7, nombre='Colon', municipio=mun_ch),
            ConsejoPopular(numero=8, nombre='El Fanguito', municipio=mun_plaza),
            ConsejoPopular(numero=9, nombre='Vedado', municipio=mun_plaza),
            ConsejoPopular(numero=10, nombre='Nuevo Vedado', municipio=mun_plaza),
            ConsejoPopular(numero=11, nombre='Miramar', municipio=mun_playa),
            ConsejoPopular(numero=12, nombre='Buena Vista', municipio=mun_playa),
            ConsejoPopular(numero=13, nombre='Flores', municipio=mun_playa),
            ConsejoPopular(numero=14, nombre='Cubanacan', municipio=mun_playa),
        ])
    else:
        pass

    if not Concepto.objects.all().exists():
        Concepto.objects.bulk_create([
            Concepto(nombre='Propiedad'),
            Concepto(nombre='Usufructo Gratuito'),
            Concepto(nombre='Usufructo Arrendatario'),
        ])
    else:
        pass

    if not Calle.objects.all().exists():
        Calle.objects.bulk_create([
            Calle(nombre='1'),
            Calle(nombre='2'),
            Calle(nombre='3'),
            Calle(nombre='4'),
            Calle(nombre='5'),
            Calle(nombre='6'),
            Calle(nombre='7'),
            Calle(nombre='8'),
            Calle(nombre='9'),
            Calle(nombre='10'),
            Calle(nombre='11'),
            Calle(nombre='12'),
            Calle(nombre='13'),
            Calle(nombre='14'),
            Calle(nombre='15'),
            Calle(nombre='16'),
            Calle(nombre='17'),
            Calle(nombre='18'),
            Calle(nombre='19'),
            Calle(nombre='20'),
            Calle(nombre='21'),
            Calle(nombre='22'),
            Calle(nombre='23'),
            Calle(nombre='24'),
            Calle(nombre='25'),
            Calle(nombre='26-A'),
            Calle(nombre='27'),
            Calle(nombre='28'),
            Calle(nombre='29'),
            Calle(nombre='30'),
            Calle(nombre='31'),
            Calle(nombre='32'),
            Calle(nombre='33'),
            Calle(nombre='34'),
            Calle(nombre='35'),
            Calle(nombre='36'),
            Calle(nombre='37'),
            Calle(nombre='38'),
            Calle(nombre='39'),
            Calle(nombre='40'),
            Calle(nombre='41'),
            Calle(nombre='42'),
            Calle(nombre='43'),
            Calle(nombre='44'),
            Calle(nombre='45'),
            Calle(nombre='45-A'),
            Calle(nombre='46'),
            Calle(nombre='47'),
            Calle(nombre='48'),
            Calle(nombre='49'),
            Calle(nombre='50'),
            Calle(nombre='51'),
            Calle(nombre='52'),
            Calle(nombre='53'),
            Calle(nombre='54'),
            Calle(nombre='55'),
            Calle(nombre='56'),
            Calle(nombre='57'),
            Calle(nombre='58'),
            Calle(nombre='59'),
            Calle(nombre='60'),
            Calle(nombre='61'),
            Calle(nombre='62'),
            Calle(nombre='63'),
            Calle(nombre='64'),
            Calle(nombre='65'),
            Calle(nombre='66'),
            Calle(nombre='67'),
            Calle(nombre='68'),
            Calle(nombre='69'),
            Calle(nombre='70'),
            Calle(nombre='71'),
            Calle(nombre='72'),
            Calle(nombre='73'),
            Calle(nombre='74'),
            Calle(nombre='75'),
            Calle(nombre='76'),
            Calle(nombre='77'),
            Calle(nombre='78'),
            Calle(nombre='79'),
            Calle(nombre='80'),
            Calle(nombre='81'),
            Calle(nombre='82'),
            Calle(nombre='83'),
            Calle(nombre='84'),
            Calle(nombre='85'),
            Calle(nombre='86'),
            Calle(nombre='87'),
            Calle(nombre='88'),
            Calle(nombre='89'),
            Calle(nombre='90'),
            Calle(nombre='91'),
            Calle(nombre='92'),
            Calle(nombre='93'),
            Calle(nombre='94'),
            Calle(nombre='95'),
            Calle(nombre='96'),
            Calle(nombre='97'),
            Calle(nombre='98'),
            Calle(nombre='99'),
            Calle(nombre='100'),
            Calle(nombre='101'),
            Calle(nombre='102'),
            Calle(nombre='103'),
            Calle(nombre='104'),
            Calle(nombre='105'),
            Calle(nombre='106'),
            Calle(nombre='107'),
            Calle(nombre='108'),
            Calle(nombre='109'),
            Calle(nombre='110'),
            Calle(nombre='111'),
            Calle(nombre='112'),
            Calle(nombre='113'),
            Calle(nombre='114'),
            Calle(nombre='115'),
            Calle(nombre='116'),
            Calle(nombre='117'),
            Calle(nombre='118'),
            Calle(nombre='119'),
            Calle(nombre='120'),
            Calle(nombre='121'),
            Calle(nombre='122'),
            Calle(nombre='123'),
            Calle(nombre='124'),
            Calle(nombre='125'),
            Calle(nombre='126'),
            Calle(nombre='127'),
            Calle(nombre='128'),
            Calle(nombre='129'),
            Calle(nombre='130'),
            Calle(nombre='131'),
            Calle(nombre='132'),
            Calle(nombre='133'),
            Calle(nombre='134'),
            Calle(nombre='135'),
            Calle(nombre='136'),
            Calle(nombre='137'),
            Calle(nombre='138'),
            Calle(nombre='139'),
            Calle(nombre='140'),
            Calle(nombre='141'),
            Calle(nombre='142'),
            Calle(nombre='143'),
            Calle(nombre='144'),
            Calle(nombre='145'),
            Calle(nombre='146'),
            Calle(nombre='147'),
            Calle(nombre='148'),
            Calle(nombre='149'),
            Calle(nombre='150'),
            Calle(nombre='151'),
            Calle(nombre='152'),
            Calle(nombre='153'),
            Calle(nombre='154'),
            Calle(nombre='155'),
            Calle(nombre='156'),
            Calle(nombre='157'),
            Calle(nombre='158'),
            Calle(nombre='159'),
            Calle(nombre='160'),
            Calle(nombre='161'),
            Calle(nombre='162'),
            Calle(nombre='163'),
            Calle(nombre='164'),
            Calle(nombre='165'),
            Calle(nombre='166'),
            Calle(nombre='167'),
            Calle(nombre='168'),
            Calle(nombre='169'),
            Calle(nombre='170'),
            Calle(nombre='171'),
            Calle(nombre='172'),
            Calle(nombre='173'),
            Calle(nombre='174'),
            Calle(nombre='175'),
            Calle(nombre='176'),
            Calle(nombre='177'),
            Calle(nombre='178'),
            Calle(nombre='179'),
            Calle(nombre='180'),
            Calle(nombre='181'),
            Calle(nombre='182'),
            Calle(nombre='183'),
            Calle(nombre='184'),
            Calle(nombre='185'),
            Calle(nombre='186'),
            Calle(nombre='187'),
            Calle(nombre='188'),
            Calle(nombre='189'),
            Calle(nombre='190'),
            Calle(nombre='191'),
            Calle(nombre='192'),
            Calle(nombre='193'),
            Calle(nombre='194'),
            Calle(nombre='195'),
            Calle(nombre='196'),
            Calle(nombre='197'),
            Calle(nombre='198'),
            Calle(nombre='199'),
            Calle(nombre='200'),
            Calle(nombre='201'),
            Calle(nombre='202'),
            Calle(nombre='203'),
            Calle(nombre='204'),
            Calle(nombre='205'),
            Calle(nombre='206'),
            Calle(nombre='207'),
            Calle(nombre='208'),
            Calle(nombre='209'),
            Calle(nombre='210'),
            Calle(nombre='211'),
            Calle(nombre='212'),
            Calle(nombre='213'),
            Calle(nombre='214'),
            Calle(nombre='215'),
            Calle(nombre='216'),
            Calle(nombre='217'),
            Calle(nombre='218'),
            Calle(nombre='219'),
            Calle(nombre='220'),
            Calle(nombre='221'),
            Calle(nombre='222'),
            Calle(nombre='223'),
            Calle(nombre='224'),
            Calle(nombre='225'),
            Calle(nombre='226'),
            Calle(nombre='227'),
            Calle(nombre='228'),
            Calle(nombre='229'),
            Calle(nombre='230'),
            Calle(nombre='231'),
            Calle(nombre='232'),
            Calle(nombre='233'),
            Calle(nombre='234'),
            Calle(nombre='235'),
            Calle(nombre='236'),
            Calle(nombre='237'),
            Calle(nombre='238'),
            Calle(nombre='239'),
            Calle(nombre='240'),
            Calle(nombre='241'),
            Calle(nombre='242'),
            Calle(nombre='243'),
            Calle(nombre='244'),
            Calle(nombre='245'),
            Calle(nombre='246'),
            Calle(nombre='247'),
            Calle(nombre='248'),
            Calle(nombre='249'),
            Calle(nombre='250'),
            Calle(nombre='251'),
            Calle(nombre='252'),
            Calle(nombre='253'),
            Calle(nombre='254'),
            Calle(nombre='255'),
            Calle(nombre='256'),
            Calle(nombre='257'),
            Calle(nombre='258'),
            Calle(nombre='259'),
            Calle(nombre='260'),
            Calle(nombre='261'),
            Calle(nombre='262'),
            Calle(nombre='263'),
            Calle(nombre='264'),
            Calle(nombre='265'),
            Calle(nombre='266'),
            Calle(nombre='267'),
            Calle(nombre='268'),
            Calle(nombre='269'),
            Calle(nombre='270'),
            Calle(nombre='271'),
            Calle(nombre='272'),
            Calle(nombre='273'),
            Calle(nombre='274'),
            Calle(nombre='275'),
            Calle(nombre='276'),
            Calle(nombre='277'),
            Calle(nombre='278'),
            Calle(nombre='279'),
            Calle(nombre='280'),
            Calle(nombre='281'),
            Calle(nombre='282'),
            Calle(nombre='283'),
            Calle(nombre='284'),
            Calle(nombre='285'),
            Calle(nombre='286'),
            Calle(nombre='287'),
            Calle(nombre='288'),
            Calle(nombre='289'),
            Calle(nombre='290'),
            Calle(nombre='291'),
            Calle(nombre='292'),
            Calle(nombre='293'),
            Calle(nombre='294'),
            Calle(nombre='295'),
            Calle(nombre='296'),
            Calle(nombre='297'),
            Calle(nombre='298'),
            Calle(nombre='299'),
            Calle(nombre='300'),
            Calle(nombre='301'),
            Calle(nombre='302'),
            Calle(nombre='303'),
            Calle(nombre='304'),
            Calle(nombre='305'),
            Calle(nombre='306'),
            Calle(nombre='307'),
            Calle(nombre='308'),
            Calle(nombre='309'),
            Calle(nombre='310'),
            Calle(nombre='311'),
            Calle(nombre='312'),
            Calle(nombre='313'),
            Calle(nombre='314'),
            Calle(nombre='315'),
            Calle(nombre='316'),
            Calle(nombre='317'),
            Calle(nombre='318'),
            Calle(nombre='319'),
            Calle(nombre='320'),
            Calle(nombre='321'),
            Calle(nombre='322'),
            Calle(nombre='323'),
            Calle(nombre='324'),
            Calle(nombre='325'),
            Calle(nombre='326'),
            Calle(nombre='327'),
            Calle(nombre='328'),
            Calle(nombre='329'),
            Calle(nombre='330'),
            Calle(nombre='331'),
            Calle(nombre='332'),
            Calle(nombre='333'),
            Calle(nombre='334'),
            Calle(nombre='335'),
            Calle(nombre='336'),
            Calle(nombre='337'),
            Calle(nombre='338'),
            Calle(nombre='339'),
            Calle(nombre='340'),
            Calle(nombre='341'),
            Calle(nombre='342'),
            Calle(nombre='343'),
            Calle(nombre='344'),
            Calle(nombre='345'),
            Calle(nombre='346'),
            Calle(nombre='347'),
            Calle(nombre='348'),
            Calle(nombre='349'),
            Calle(nombre='350'),
            Calle(nombre='351'),
            Calle(nombre='352'),
            Calle(nombre='353'),
            Calle(nombre='354'),
            Calle(nombre='355'),
            Calle(nombre='356'),
            Calle(nombre='357'),
            Calle(nombre='358'),
            Calle(nombre='359'),
            Calle(nombre='360'),
            Calle(nombre='361'),
            Calle(nombre='362'),
            Calle(nombre='363'),
            Calle(nombre='364'),
            Calle(nombre='365'),
            Calle(nombre='366'),
            Calle(nombre='367'),
            Calle(nombre='368'),
            Calle(nombre='369'),
            Calle(nombre='370'),
            Calle(nombre='371'),
            Calle(nombre='372'),
            Calle(nombre='373'),
            Calle(nombre='374'),
            Calle(nombre='375'),
            Calle(nombre='376'),
            Calle(nombre='377'),
            Calle(nombre='378'),
            Calle(nombre='379'),
            Calle(nombre='380'),
            Calle(nombre='381'),
            Calle(nombre='382'),
            Calle(nombre='383'),
            Calle(nombre='384'),
            Calle(nombre='385'),
            Calle(nombre='386'),
            Calle(nombre='387'),
            Calle(nombre='388'),
            Calle(nombre='389'),
            Calle(nombre='390'),
            Calle(nombre='391'),
            Calle(nombre='392'),
            Calle(nombre='393'),
            Calle(nombre='394'),
            Calle(nombre='395'),
            Calle(nombre='396'),
            Calle(nombre='397'),
            Calle(nombre='398'),
            Calle(nombre='399'),
            Calle(nombre='400'),
            Calle(nombre='401'),
            Calle(nombre='402'),
            Calle(nombre='403'),
            Calle(nombre='404'),
            Calle(nombre='405'),
            Calle(nombre='406'),
            Calle(nombre='407'),
            Calle(nombre='408'),
            Calle(nombre='409'),
            Calle(nombre='410'),
            Calle(nombre='411'),
            Calle(nombre='412'),
            Calle(nombre='413'),
            Calle(nombre='414'),
            Calle(nombre='415'),
            Calle(nombre='416'),
            Calle(nombre='417'),
            Calle(nombre='418'),
            Calle(nombre='419'),
            Calle(nombre='420'),
            Calle(nombre='421'),
            Calle(nombre='422'),
            Calle(nombre='423'),
            Calle(nombre='424'),
            Calle(nombre='425'),
            Calle(nombre='426'),
            Calle(nombre='427'),
            Calle(nombre='428'),
            Calle(nombre='429'),
            Calle(nombre='430'),
            Calle(nombre='431'),
            Calle(nombre='432'),
            Calle(nombre='433'),
            Calle(nombre='434'),
            Calle(nombre='435'),
            Calle(nombre='436'),
            Calle(nombre='437'),
            Calle(nombre='438'),
            Calle(nombre='439'),
            Calle(nombre='440'),
            Calle(nombre='441'),
            Calle(nombre='442'),
            Calle(nombre='443'),
            Calle(nombre='444'),
            Calle(nombre='445'),
            Calle(nombre='446'),
            Calle(nombre='447'),
            Calle(nombre='448'),
            Calle(nombre='449'),
            Calle(nombre='450'),
            Calle(nombre='451'),
            Calle(nombre='452'),
            Calle(nombre='453'),
            Calle(nombre='454'),
            Calle(nombre='455'),
            Calle(nombre='456'),
            Calle(nombre='457'),
            Calle(nombre='458'),
            Calle(nombre='459'),
            Calle(nombre='460'),
            Calle(nombre='461'),
            Calle(nombre='462'),
            Calle(nombre='463'),
            Calle(nombre='464'),
            Calle(nombre='465'),
            Calle(nombre='466'),
            Calle(nombre='467'),
            Calle(nombre='468'),
            Calle(nombre='469'),
            Calle(nombre='470'),
            Calle(nombre='471'),
            Calle(nombre='472'),
            Calle(nombre='473'),
            Calle(nombre='474'),
            Calle(nombre='475'),
            Calle(nombre='476'),
            Calle(nombre='477'),
            Calle(nombre='478'),
            Calle(nombre='479'),
            Calle(nombre='480'),
            Calle(nombre='481'),
            Calle(nombre='482'),
            Calle(nombre='483'),
            Calle(nombre='484'),
            Calle(nombre='485'),
            Calle(nombre='486'),
            Calle(nombre='487'),
            Calle(nombre='488'),
            Calle(nombre='489'),
            Calle(nombre='490'),
            Calle(nombre='491'),
            Calle(nombre='492'),
            Calle(nombre='493'),
            Calle(nombre='494'),
            Calle(nombre='495'),
            Calle(nombre='496'),
            Calle(nombre='497'),
            Calle(nombre='498'),
            Calle(nombre='499'),
            Calle(nombre='500'),
            Calle(nombre='1ra'),
            Calle(nombre='1ra A'),
            Calle(nombre='1ra B'),
            Calle(nombre='3ra'),
            Calle(nombre='3ra A'),
            Calle(nombre='5ta'),
            Calle(nombre='5ta A'),
            Calle(nombre='5ta B'),
            Calle(nombre='5ta C'),
            Calle(nombre='5ta D'),
            Calle(nombre='5ta E'),
            Calle(nombre='5ta F'),
            Calle(nombre='7ma'),
            Calle(nombre='7ma A'),
            Calle(nombre='7ma B'),
            Calle(nombre='9na'),
            Calle(nombre='9na A'),
            Calle(nombre='9na B'),
            Calle(nombre='Avenida del Puerto'),
            Calle(nombre='Cuba'),
            Calle(nombre='Aguiar'),
            Calle(nombre='Compostela'),
            Calle(nombre='Habana'),
            Calle(nombre="O'Reilly"),
            Calle(nombre='Obispo'),
            Calle(nombre='Capdevila (Carcel)'),
            Calle(nombre='Obrapía'),
            Calle(nombre='Lamparilla'),
            Calle(nombre='Amargura'),
            Calle(nombre='Soledad'),
            Calle(nombre='Sol'),
            Calle(nombre='Chacón'),
            Calle(nombre='Cuarteles'),
            Calle(nombre='Merced'),
            Calle(nombre='Picota'),
            Calle(nombre='Luz'),
            Calle(nombre='Acosta'),
            Calle(nombre='San Izidro'),
            Calle(nombre='Empedrado'),
            Calle(nombre='San Ignacio'),
            Calle(nombre='Muralla'),
            Calle(nombre='Belen'),
            Calle(nombre='Cienfuegos'),
            Calle(nombre='Monte'),
            Calle(nombre='Chacón'),
            Calle(nombre='Tacón'),
            Calle(nombre='Mercaderes'),
            Calle(nombre='San Telmo'),
            Calle(nombre='Tejadillo'),
            Calle(nombre='San Juan de Dios'),
            Calle(nombre='Aguacate'),
            Calle(nombre='Peña Pobre'),
            Calle(nombre='Espada'),
            Calle(nombre='Villegas'),
            Calle(nombre='Bernaza'),
            Calle(nombre='Amargura'),
            Calle(nombre='Brasil (Teniente Rey)'),
            Calle(nombre='Jesús María'),
            Calle(nombre='Conde'),
            Calle(nombre='Leonor Pérez (Paula)'),
            Calle(nombre='Velazco'),
            Calle(nombre='Damas'),
            Calle(nombre='Inquisidor'),
            Calle(nombre='Oficios'),
            Calle(nombre='Churruca'),
            Calle(nombre='Curazao'),
            Calle(nombre='Cristo'),
            Calle(nombre='Avenida de BElgica (Egido)'),
            Calle(nombre='Agramonte (Zulueta)'),
            Calle(nombre='Arsenal'),
            Calle(nombre='Dragones'),
            Calle(nombre='Gloria'),
            Calle(nombre='Misión'),
            Calle(nombre='Apodaca'),
            Calle(nombre='Cárdenas'),
            Calle(nombre='Cienfuegos'),
            Calle(nombre='Corrales'),
            Calle(nombre='Economía'),
            Calle(nombre='Milicias'),
            Calle(nombre='Aponte (Someruelos)'),
            Calle(nombre='Avenida Simón Bolívar (Reina)'),
            Calle(nombre='Máximo Gómez (Monte)'),
            Calle(nombre='Factoría'),
            Calle(nombre='Suárez'),
            Calle(nombre='Esperanza'),
            Calle(nombre='Avenida de España (Vives)'),
            Calle(nombre='Revillagigedo'),
            Calle(nombre='Florida'),
            Calle(nombre='Ángeles'),
            Calle(nombre='Indio'),
            Calle(nombre='San Nicolás'),
            Calle(nombre='Recio'),
            Calle(nombre='Figuras'),
            Calle(nombre='Carmen'),
            Calle(nombre='Rastro'),
            Calle(nombre='Chamorro'),
            Calle(nombre='Puerta Cerrada'),
            Calle(nombre='Diaria'),
            Calle(nombre='Alambique'),
            Calle(nombre='Fábrica'),
            Calle(nombre='Atarés'),
            Calle(nombre='Tallapiedra'),
            Calle(nombre='Anillo del Puerto'),
            Calle(nombre='Ferrer'),
            Calle(nombre='Tenerife'),
            Calle(nombre='Desagüe'),
            Calle(nombre='Enrique Barnet (Estrella)'),
            Calle(nombre='Maloja'),
            Calle(nombre='Oquendo'),
            Calle(nombre='Marques Gonzalez'),
            Calle(nombre='San Rafael'),
            Calle(nombre='San Miguel'),
            Calle(nombre='José de San Martín (San José)'),
            Calle(nombre='San Lázaro'),
            Calle(nombre='Industría'),
            Calle(nombre='Consulado'),
            Calle(nombre='Genios'),
            Calle(nombre='Crespo'),
            Calle(nombre='Amistad'),
            Calle(nombre='Neptuno'),
            Calle(nombre='Padre Varela (Belascoain)'),
            Calle(nombre='Campanario'),
            Calle(nombre='Manrique'),
            Calle(nombre='Reunión'),
            Calle(nombre='Rayo'),
            Calle(nombre='Sitios'),
            Calle(nombre='Peñalver'),
            Calle(nombre='Condesa'),
            Calle(nombre='Concepción de la Valla'),
            Calle(nombre='Lealtad'),
            Calle(nombre='Escobar'),
            Calle(nombre='División'),
            Calle(nombre='Chávez'),
            Calle(nombre='Salud'),
            Calle(nombre='Cerrada del Paseo'),
            Calle(nombre='Gervasio'),
            Calle(nombre='Concordia'),
            Calle(nombre='Virtudes'),
            Calle(nombre='Ánimas'),
            Calle(nombre='Lagunas'),
            Calle(nombre='Perseverancia'),
            Calle(nombre='Lucena'),
            Calle(nombre='Santiago'),
            Calle(nombre='Jesús Peregrino'),
            Calle(nombre='Pocito'),
            Calle(nombre='Castillejo'),
            Calle(nombre='Aramburu'),
            Calle(nombre='Hospital'),
            Calle(nombre='Espada'),
            Calle(nombre='San Francisco'),
            Calle(nombre='Paseo de Martí (Paseo del Prado)'),
            Calle(nombre='Malecón (Avenida de Antonio Maceo)'),
            Calle(nombre='Calzada de Infanta'),
            Calle(nombre='Avenida Zanja'),
            Calle(nombre='Avenida de Italia (Galiano)'),
            Calle(nombre='Trocadero'),
            Calle(nombre='Colón'),
            Calle(nombre='Refugio'),
            Calle(nombre='Morro'),
            Calle(nombre='Blanco'),
            Calle(nombre='27 de Noviembre (Jovellar)'),
            Calle(nombre='Marina'),
            Calle(nombre='Hornos'),
            Calle(nombre='Vapor'),
            Calle(nombre='Principe'),
            Calle(nombre='Humboldt'),
            Calle(nombre='Valle'),
            Calle(nombre='Franco'),
            Calle(nombre='Subirana'),
            Calle(nombre='Árbol Seco'),
            Calle(nombre='Retiro'),
            Calle(nombre='Plasencia'),
            Calle(nombre='Santo Tomás'),
            Calle(nombre='Benjumeda'),
            Calle(nombre='Santa Marta'),
            Calle(nombre='Avenida Arroyo (Manglar)'),
            Calle(nombre='San Joaquín'),
            Calle(nombre='Amenidad'),
            Calle(nombre='Pedroso'),
            Calle(nombre='Pasaje A'),
            Calle(nombre='Pasaje B'),
            Calle(nombre='Universidad'),
            Calle(nombre='Pescado'),
            Calle(nombre='San Carlos'),
            Calle(nombre='Nueva del Pilar'),
            Calle(nombre='Lindero'),
            Calle(nombre='Mercado'),
            Calle(nombre='Manglar'),
            Calle(nombre='Matadero'),
            Calle(nombre='Omoa Este'),
            Calle(nombre='Avenida de México (Cristina)'),
            Calle(nombre='Enlace a Manglar'),
            Calle(nombre='Vigía'),
            Calle(nombre='Pila'),
            Calle(nombre='Quinta'),
            Calle(nombre='Castillo'),
            Calle(nombre='Fernandina'),
            Calle(nombre='San Ramón'),
            Calle(nombre='Pasaje Yayabo'),
            Calle(nombre='Cerrada'),
            Calle(nombre='Romay'),
            Calle(nombre='De la Quinta'),
            Calle(nombre='Calzada del 10 de Octubre'),
            Calle(nombre='Alejandro Ramírez'),
            Calle(nombre='Francisco'),
            Calle(nombre='Calzada del Cerro'),
            Calle(nombre='Velázquez'),
            Calle(nombre='Zequeira'),
            Calle(nombre='Cádiz'),
            Calle(nombre='Santa Rosa'),
            Calle(nombre='San Jacinto'),
            Calle(nombre='Estévez'),
            Calle(nombre='Sierra'),
            Calle(nombre='San Gregorio'),
            Calle(nombre='San José'),
            Calle(nombre='Cruz del Padre'),
            Calle(nombre='Barbería'),
            Calle(nombre='Nueva'),
            Calle(nombre='Campos'),
            Calle(nombre='Consejero Arango'),
            Calle(nombre='20 de Mayo'),
            Calle(nombre='Rafael Rateg'),
            Calle(nombre='San Martín'),
            Calle(nombre='Aranguren (Zaldo)'),
            Calle(nombre='Línea del Ferrocarril'),
            Calle(nombre='Barreiro'),
            Calle(nombre='Pereira'),
            Calle(nombre='P. Lacoste'),
            Calle(nombre='Factor'),
            Calle(nombre='Panchito Gómez'),
            Calle(nombre='Masó'),
            Calle(nombre='Marta Abreu'),
            Calle(nombre='General E Nuñez'),
            Calle(nombre='Enrique Villaundas'),
            Calle(nombre='Nestor Sardiñas'),
            Calle(nombre='Amezaga'),
            Calle(nombre='Almendares'),
            Calle(nombre='Bruzón'),
            Calle(nombre='Luaces'),
            Calle(nombre='Lugareño'),
            Calle(nombre='Requena'),
            Calle(nombre='C Morales'),
            Calle(nombre='Montoro'),
            Calle(nombre='Avenida Salvador Allende (Carlos III)'),
            Calle(nombre='Ayestaran'),
            Calle(nombre='Dominguez'),
            Calle(nombre='Calle Clavel'),
            Calle(nombre='Xifré'),
            Calle(nombre='Pozos Dulces'),
            Calle(nombre='19 de Mayo'),
            Calle(nombre='Territorial'),
            Calle(nombre='General Suárez'),
            Calle(nombre='Avenida Independencia'),
            Calle(nombre='City Hall'),
            Calle(nombre='Ayuntamiento'),
            Calle(nombre='San Pedro'),
            Calle(nombre='Lombillo'),
            Calle(nombre='Ermita'),
            Calle(nombre='La Rosa'),
            Calle(nombre='Tulipán'),
            Calle(nombre='Central'),
            Calle(nombre='Conil'),
            Calle(nombre='Santa Ana'),
            Calle(nombre='Marquez'),
            Calle(nombre='Talleres (Carmen)'),
            Calle(nombre='Peñón'),
            Calle(nombre='Manila'),
            Calle(nombre='Monasterio'),
            Calle(nombre='Santa Teresa'),
            Calle(nombre='Zaragoza'),
            Calle(nombre='Arzobispo'),
            Calle(nombre='Zanja Real'),
            Calle(nombre='Falgueras'),
            Calle(nombre='Concepción'),
            Calle(nombre='Mariano'),
            Calle(nombre='Piñeras'),
            Calle(nombre='San Pablo'),
            Calle(nombre='Vista Hermosa'),
            Calle(nombre='Auditor'),
            Calle(nombre='Pedro Pérez'),
            Calle(nombre='Cocos'),
            Calle(nombre='Santovenia'),
            Calle(nombre='Unión y Ahorro'),
            Calle(nombre='Patria'),
            Calle(nombre='Carballo'),
            Calle(nombre='Munguia'),
            Calle(nombre='Borrego'),
            Calle(nombre='Saravia'),
            Calle(nombre='Calzada de Buenos Aires'),
            Calle(nombre='Echevarría'),
            Calle(nombre='Trinidad'),
            Calle(nombre='Herrera'),
            Calle(nombre='Carbajal'),
            Calle(nombre='Leonor'),
            Calle(nombre='Diana'),
            Calle(nombre='Agua Dulce'),
            Calle(nombre='Albear'),
            Calle(nombre='San Quintín'),
            Calle(nombre='Serafines'),
            Calle(nombre='San Julio'),
            Calle(nombre='San Gabriel'),
            Calle(nombre='Magnolia'),
            Calle(nombre='Macedonia'),
            Calle(nombre='Balaguer'),
            Calle(nombre='General Serrano'),
            Calle(nombre='Flores'),
            Calle(nombre='Tamarindo'),
            Calle(nombre='San Benigno'),
            Calle(nombre='San Indalecio'),
            Calle(nombre='Rabí'),
            Calle(nombre='Cerezo'),
            Calle(nombre='San Anselmo'),
            Calle(nombre='Florencia'),
            Calle(nombre='Ángel'),
            Calle(nombre='Durege'),
            Calle(nombre='Salvador'),
            Calle(nombre='Armonía'),
            Calle(nombre='Bella Vista'),
            Calle(nombre='Resguardo'),
            Calle(nombre='Parque'),
            Calle(nombre='Cepero'),
            Calle(nombre='Perkins'),
            Calle(nombre='Recreo'),
            Calle(nombre='Suzarte'),
            Calle(nombre='Chaple'),
            Calle(nombre='Calzada de Palatino'),
            Calle(nombre='Meireles'),
            Calle(nombre='Atocha'),
            Calle(nombre='Paniagua'),
            Calle(nombre='Reyes'),
            Calle(nombre='Empresa'),
            Calle(nombre='Cintra'),
            Calle(nombre='Cañongo'),
            Calle(nombre='Daoiz'),
            Calle(nombre='Infanta'),
            Calle(nombre='Pezuela'),
            Calle(nombre='Washington'),
            Calle(nombre='Velarde'),
            Calle(nombre='Primelles'),
            Calle(nombre='Prensa'),
            Calle(nombre='Pizarro'),
            Calle(nombre='San Cristobal'),
            Calle(nombre='Habana Park'),
            Calle(nombre='Sánchez'),
            Calle(nombre='Avenida de la Independencia (Avenida de Rancho Boyeros)'),
            Calle(nombre='Avenida Carlos Manuel de Céspedes'),
            Calle(nombre='Concha'),
            Calle(nombre='Genral Aguirre'),
            Calle(nombre='H. Upmann'),
            Calle(nombre='Mazón'),
            Calle(nombre='Aquirre'),
            Calle(nombre='Basarrate'),
            Calle(nombre='Avenida Universidad'),
            Calle(nombre='Ronda'),
            Calle(nombre='Calzada de Zapata'),
            Calle(nombre='Via Blanca'),
            Calle(nombre='Ave. de los Precidentes (G)'),
            Calle(nombre='Paseo'),
            Calle(nombre='Julia Borges'),
            Calle(nombre='Panorama'),
            Calle(nombre='Protestantes'),
            Calle(nombre='Loma'),
            Calle(nombre='Avenida de Colón'),
            Calle(nombre='Callejon de los Protestantes'),
            Calle(nombre='Conill A'),
            Calle(nombre='Avenida Kohly'),
            Calle(nombre='Norte'),
            Calle(nombre='Avenida Parque'),
            Calle(nombre='Avenida de la Loma'),
            Calle(nombre='Avenida del Río'),
            Calle(nombre='Mazarredo'),
            Calle(nombre='Reparto'),
            Calle(nombre='Recurso'),
            Calle(nombre='Empino'),
            Calle(nombre='Santa María'),
            Calle(nombre='Ulloa'),
            Calle(nombre='Calzada de Puentes Grandes (Avenida 51)'),
            Calle(nombre='Avenida del Bosque'),
            Calle(nombre='Edison Sur'),
            Calle(nombre='Avenida Zoológico'),
            Calle(nombre='Pasaje Crecherie'),
            Calle(nombre='Línea'),
            Calle(nombre='Calzada'),
            Calle(nombre='Ensenada'),
            Calle(nombre='Villanueva'),
            Calle(nombre='San Felipe'),
            Calle(nombre='Jesús López Camino (Gancedo)'),
            Calle(nombre='Justicia'),
            Calle(nombre='Arango'),
            Calle(nombre='Enna'),
            Calle(nombre='Municipio'),
            Calle(nombre='Guasabacoa'),
            Calle(nombre='Reforma'),
            Calle(nombre='Melones'),
            Calle(nombre='Santa Felicia'),
            Calle(nombre='Compromiso'),
            Calle(nombre='Rosa Enríquez'),
            Calle(nombre='Fomento'),
            Calle(nombre='Rodríquez Este'),
            Calle(nombre='Alcoy'),
            Calle(nombre='Capricho'),
            Calle(nombre='Ramón Pintó (Calzada de Concha)'),
            Calle(nombre='Acierto'),
            Calle(nombre='Luco'),
            Calle(nombre='Pérez'),
            Calle(nombre='Calzada de Luyanó'),
            Calle(nombre='Pamplona'),
            Calle(nombre='Delicias'),
            Calle(nombre='Madrid'),
            Calle(nombre='Marqués de la Torre'),
            Calle(nombre='Princesa'),
            Calle(nombre='Mangos'),
            Calle(nombre='Remedios'),
            Calle(nombre='Blanquizal'),
            Calle(nombre='Quiroga'),
            Calle(nombre='Santa Irene'),
            Calle(nombre='Correa'),
            Calle(nombre='Encarnación'),
            Calle(nombre='Zapote'),
            Calle(nombre='San Bernardino'),
            Calle(nombre='Santa Emilia'),
            Calle(nombre='Enamorados'),
            Calle(nombre='Santos Suárez'),
            Calle(nombre='San Leonardo'),
            Calle(nombre='Paz'),
            Calle(nombre='General Lee'),
            Calle(nombre='Mayía Rodríguez'),
            Calle(nombre='Infante'),
            Calle(nombre='Goucuría'),
            Calle(nombre='Norte'),
            Calle(nombre='Juan Delagado'),
            Calle(nombre='Pasaje Este'),
            Calle(nombre='Lasola'),
            Calle(nombre='Mendoza'),
            Calle(nombre='Pasaje Oeste'),
            Calle(nombre='Luis Estévez'),
            Calle(nombre='J. H. Goss'),
            Calle(nombre='Estrada Palma'),
            Calle(nombre='Pasaje Sur'),
            Calle(nombre='Libertad'),
            Calle(nombre='Línea del Oeste'),
            Calle(nombre='Juan Lefont'),
            Calle(nombre='Pasaje Unión'),
            Calle(nombre='Johnson'),
            Calle(nombre='Milagros'),
            Calle(nombre='Calzada de Vento'),
            Calle(nombre='Avenida Santa Catalina'),
            Calle(nombre='Graciela'),
            Calle(nombre="D'Strampes"),
            Calle(nombre='Figueroa'),
            Calle(nombre='Jose A Cortina'),
            Calle(nombre='Juan Bruno Zayas'),
            Calle(nombre='José de la Luz y Caballero'),
            Calle(nombre='Consejal Viega'),
            Calle(nombre='General Lacret'),
            Calle(nombre="Alcalde O'Farrill"),
            Calle(nombre='Heredia'),
            Calle(nombre='Morell'),
            Calle(nombre='Pasage General Lee'),
            Calle(nombre='Centurión'),
            Calle(nombre='Felipe Poey'),
            Calle(nombre='Continental'),
            Calle(nombre='Pasaje San Carlos'),
            Calle(nombre='Parraga'),
            Calle(nombre='Milagros Este'),
            Calle(nombre='Buenaventura'),
            Calle(nombre='Dolores (Camilo Cienfuegos)'),
            Calle(nombre='Tejar'),
            Calle(nombre='San Anastacio'),
            Calle(nombre='Loynaz'),
            Calle(nombre='Brina'),
            Calle(nombre='Avellano'),
            Calle(nombre='Lawton'),
            Calle(nombre='María Regla'),
            Calle(nombre='Martinez'),
            Calle(nombre='Porvenir'),
            Calle(nombre='Armas'),
            Calle(nombre='Inés María'),
            Calle(nombre='Juan Alonso'),
            Calle(nombre='J Jose'),
            Calle(nombre='Font'),
            Calle(nombre='Fonts'),
            Calle(nombre='Coumbre'),
            Calle(nombre='General Bouza'),
            Calle(nombre='Pastrana'),
            Calle(nombre='Dren'),
            Calle(nombre='Teresa Blanco'),
            Calle(nombre='Jardines'),
            Calle(nombre='Tres Palacios'),
            Calle(nombre='Nivel'),
            Calle(nombre='Pedro Pernas'),
            Calle(nombre='Matías Infanzón'),
            Calle(nombre='Reglita'),
            Calle(nombre='Los Benavides'),
            Calle(nombre='Armenteros'),
            Calle(nombre='Narciso López'),
            Calle(nombre='A'),
            Calle(nombre='B'),
            Calle(nombre='C'),
            Calle(nombre='D'),
            Calle(nombre='E'),
            Calle(nombre='F'),
            Calle(nombre='G'),
            Calle(nombre='H'),
            Calle(nombre='I'),
            Calle(nombre='J'),
            Calle(nombre='K'),
            Calle(nombre='L'),
            Calle(nombre='M'),
            Calle(nombre='N'),
            Calle(nombre='O'),
            Calle(nombre='P'),
            Calle(nombre='Q'),
            Calle(nombre='R'),
            Calle(nombre='S'),
            Calle(nombre='T'),
            Calle(nombre='U'),
            Calle(nombre='V'),
            Calle(nombre='W'),
            Calle(nombre='X'),
            Calle(nombre='Y'),
            Calle(nombre='Z'),
        ])
    else:
        pass

    if not Piso.objects.all().exists():
        Piso.objects.bulk_create([
            Piso(nombre='Zotano'),
            Piso(nombre='Planta Baja'),
            Piso(nombre='1er Piso'),
            Piso(nombre='2do Piso'),
            Piso(nombre='3er Piso'),
            Piso(nombre='4to Piso'),
            Piso(nombre='5to Piso'),
            Piso(nombre='6to Piso'),
            Piso(nombre='7mo Piso'),
            Piso(nombre='8vo Piso'),
            Piso(nombre='Azotea'),
        ])
    else:
        pass

    if not CentroTrabajo.objects.all().exists():
        mun_playa = Municipio.objects.get(nombre='Playa')
        mun_plaza = Municipio.objects.get(nombre='Plaza de la Revolución')
        mun_cerro = Municipio.objects.get(nombre='Cerro')
        mun_ch = Municipio.objects.get(nombre='Centro Habana')
        CentroTrabajo.objects.bulk_create([
            CentroTrabajo(nombre='Dirección Provincialde Vivienda La Habana', siglas='DPVHAB',
                          numero=16, oc=True, municipio=mun_plaza),
            CentroTrabajo(nombre='Dirección Municipal de Vivienda Plaza de la Revolución', siglas='DMVPLZ',
                          numero=1, oc=False, municipio=mun_plaza),
            CentroTrabajo(nombre='Dirección Municipal de Vivienda Playa', siglas='DMVPLY',
                          numero=2, oc=False, municipio=mun_playa),
            CentroTrabajo(nombre='Dirección Municipal de Vivienda Cerro', siglas='DMVCER',
                          numero=3, oc=False, municipio=mun_cerro),
            CentroTrabajo(nombre='Dirección Municipal de Vivienda Centro Habana', siglas='DMVCHA',
                          numero=4, oc=False, municipio=mun_ch),
        ])
    else:
        pass

    if not AreaTrabajo.objects.all().exists():
        AreaTrabajo.objects.bulk_create([
            AreaTrabajo(nombre='Dirección Geneneral', numero=1),
            AreaTrabajo(nombre='Subdirección de Informática', numero=2),
            AreaTrabajo(nombre='Depto. de Informática', numero=3),
            AreaTrabajo(nombre='Subdirección de Economía', numero=4),
            AreaTrabajo(nombre='Depto. de Economía', numero=5),
            AreaTrabajo(nombre='Depto. de Recursos Humanos', numero=6),
            AreaTrabajo(nombre='Depto. de Atención a la Población', numero=7),
            AreaTrabajo(nombre='Depto. de Subcidios', numero=8),
        ])
    else:
        pass

    if not Organizacion.objects.all().exists():
        Organizacion.objects.bulk_create([
            Organizacion(nombre='Unión de Jovenes de Cuba (UJC)'),
            Organizacion(nombre='Partido Comunista de Cuba (PCC)'),
            Organizacion(nombre='Organización de Pioneros Jose Martí (OPJM)'),
            Organizacion(nombre='Federación de Estudiantes Universitarios (FEU)'),
            Organizacion(nombre='Federación de Estudiantes de la Enseñanza Media (FEEM)'),
            Organizacion(nombre='Central de Trabajadores de Cuba (CTC)'),
            Organizacion(nombre='Comité de Defensa de la Revolución (CDR)'),
            Organizacion(nombre='Federación de Mujeres de Cuba (FMC)'),
        ])
    else:
        pass

    if not Genero.objects.all().exists():
        Genero.objects.bulk_create([
            Genero(nombre='Femenino', sigla='F'),
            Genero(nombre='Masculino', sigla='M'),
            Genero(nombre='Otro', sigla='O'),
        ])
    else:
        pass

    if not CodificadorAsunto.objects.all().exists():
        CodificadorAsunto.objects.bulk_create([
            CodificadorAsunto(nombre='inmuebles (Casas, Departamentos, Ciudadelas, etc..)', numero=101),
            CodificadorAsunto(nombre='Ampliaciones', numero=102),
            CodificadorAsunto(nombre='Permuta entre particulares', numero=103),
            CodificadorAsunto(nombre='Permuta entre particulares y el estado', numero=104),
            CodificadorAsunto(nombre='Albergues', numero=105),
            CodificadorAsunto(nombre='Inversión y rehabilitación de vivienda', numero=106),
            CodificadorAsunto(nombre="""Materiales de construcción (Comissiones de dsitribución centros expendedores, 
                                     etc...)""", numero=107),
            CodificadorAsunto(nombre='Reparaciones y construcciones (Núcleo Familiar)', numero=108),
            CodificadorAsunto(nombre="""Reparaciones y contrucciones colectivas (edificios multifamiliares, ciudadelas, 
                                     etc...)""", numero=109),
            CodificadorAsunto(nombre='Créditos', numero=110),
            CodificadorAsunto(nombre='Incorporación a microbrigadas bajo costo propio o esfuerzo propio', numero=111),
        ])
    else:
        pass

    if not TipoQueja.objects.all().exists():
        TipoQueja.objects.bulk_create([
            TipoQueja(nombre='Denuncia', numero=1),
            TipoQueja(nombre='Consulta', numero=2),
            TipoQueja(nombre='Queja', numero=3),
        ])
    else:
        pass

    if not TipoProcedencia.objects.all().exists():
        TipoProcedencia.objects.bulk_create([
            TipoProcedencia(id=1, nombre='Anónimo', cant_dias=30, enviar=True),
            TipoProcedencia(id=2, nombre='Prensa Escrita', cant_dias=30, enviar=True),
            TipoProcedencia(id=3, nombre='Personal', cant_dias=30, enviar=True),
            TipoProcedencia(id=4, nombre='Teléfono', cant_dias=30, enviar=False),
            TipoProcedencia(id=5, nombre='Correo', cant_dias=30, enviar=True),
            TipoProcedencia(id=6, nombre='Empresa', cant_dias=30, enviar=True),
            TipoProcedencia(id=7, nombre='Organización', cant_dias=30, enviar=True),
            TipoProcedencia(id=8, nombre='Organismo', cant_dias=30, enviar=True),
            TipoProcedencia(id=9, nombre='Web', cant_dias=30, enviar=True),
        ])
    else:
        pass

    if not Estado.objects.all().exists():
        Estado.objects.bulk_create([
            Estado(id=1, nombre='Radicada'),
            Estado(id=2, nombre='Asignada'),
            Estado(id=3, nombre='En proceso'),
            Estado(id=4, nombre='Pendiente de Aprobación Jefe'),
            Estado(id=5, nombre='Pendiente de Aprobación Dir.'),
            Estado(id=6, nombre='Pendiente de Notificación'),
            Estado(id=7, nombre='Concluida'),
            Estado(id=8, nombre='Trasladada'),
            Estado(id=9, nombre='Rechazada'),
            Estado(id=10, nombre='Respuesta Rechazada'),
            Estado(id=11, nombre='Sin Estado'),
        ])
    else:
        pass

    if not Procedencia.objects.all().exists():
        Procedencia.objects.bulk_create([
            # Procedencia(nombre='', enviar=True, tipo=, tipo_contenido=, id_objecto=, objecto_contenido=),
        ])
    else:
        pass

    if not ClasificacionRespuesta.objects.all().exists():
        ClasificacionRespuesta.objects.bulk_create([
            ClasificacionRespuesta(nombre='Solucionada', codigo='S'),
            ClasificacionRespuesta(nombre='Pendiente Solución', codigo='PS'),
            ClasificacionRespuesta(nombre='Explicada Causa de No Solución', codigo='ECNS'),
        ])
    else:
        pass

    if not PrensaEscrita.objects.all().exists():
        PrensaEscrita.objects.bulk_create([
            PrensaEscrita(nombre='Periódico Gramma', siglas='GRM'),
            PrensaEscrita(nombre='Revista Mujeres', siglas='MUJ'),
        ])
    else:
        pass

    if Calle.objects.exists() and Municipio.objects.exists():
        for mun in Municipio.objects.exclude(
                Q(nombre__icontains="centro habana") | Q(nombre__icontains="habana vieja")):
            mun.calle_set.set(Calle.objects.filter(id__gte="30"))
        Municipio.objects.filter(nombre__icontains="centro habana").first().calle_set.set(
            Calle.objects.filter(id__in=[33, 34, 35, ])
        )
