# Generated by Django 2.2.2 on 2020-03-29 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0015_auto_20200211_1344'),
        ('dpv_documento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpvdocumento',
            options={'ordering': ('-fecha_registro', 'no_registro'), 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AddField(
            model_name='dpvdocumento',
            name='dir_calle',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_dir_calle', to='dpv_nomencladores.Calle', verbose_name='Direccion Calle'),
        ),
        migrations.AddField(
            model_name='dpvdocumento',
            name='dir_cpopular',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_dir_cpopular', to='dpv_nomencladores.ConsejoPopular', verbose_name='Direccion Consejo Popular'),
        ),
        migrations.AddField(
            model_name='dpvdocumento',
            name='dir_entrecalle1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_dir_entrecalle1', to='dpv_nomencladores.Calle', verbose_name='Direccion Primera entrecalle'),
        ),
        migrations.AddField(
            model_name='dpvdocumento',
            name='dir_entrecalle2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_dir_entrecalle2', to='dpv_nomencladores.Calle', verbose_name='Direccion Segunda Entrecalle'),
        ),
        migrations.AddField(
            model_name='dpvdocumento',
            name='dir_numero',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='Direccion Numero'),
        ),
        migrations.AddField(
            model_name='dpvdocumento',
            name='respuesta_a',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_dir_cpopular', to='dpv_nomencladores.RespuestaAQueja', verbose_name='Direccion Consejo Popular'),
        ),
    ]
