# Generated by Django 2.2.2 on 2020-05-17 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_documento', '0002_auto_20200329_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpvdocumento',
            name='municipio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.Municipio', verbose_name='Municipio'),
        ),
    ]
