# Generated by Django 2.2.2 on 2020-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_documento', '0003_auto_20200517_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodpvdocumento',
            name='dias_proceso',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Dias para procesar'),
        ),
    ]
