# Generated by Django 2.2.2 on 2020-06-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_documento', '0004_tipodpvdocumento_dias_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpvdocumento',
            name='respuesta_a',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='dpv_nomencladores.RespuestaAQueja', verbose_name='Respuesta a'),
        ),
        migrations.AlterField(
            model_name='tipodpvdocumento',
            name='dias_proceso',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Días para procesar'),
        ),
    ]
