# Generated by Django 2.2.2 on 2020-06-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_documento', '0008_auto_20200618_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpvdocumento',
            name='procedencia',
            field=models.ForeignKey(blank=True, help_text='De donde proviene el documento', null=True, on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.Procedencia', verbose_name='Procedencia'),
        ),
    ]
