# Generated by Django 2.2.2 on 2020-07-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_documento', '0005_auto_20200711_2314'),
        ('dpv_documento', '0010_auto_20200618_2109'),
    ]

    operations = [
    ]
