# Generated by Django 2.2.2 on 2021-01-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_documento', '0011_merge_20200712_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpvdocumento',
            name='observation',
            field=models.TextField(blank=True, help_text='Observaciones relacionadas con el documento', null=True, verbose_name='Observación'),
        ),
    ]
