# Generated by Django 2.2.2 on 2021-01-28 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0034_redsocial_url'),
        ('dpv_documento', '0012_dpvdocumento_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpvdocumento',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpv_nomencladores.Lugar', verbose_name='Lugar'),
        ),
    ]
