# Generated by Django 2.2.3 on 2021-01-05 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Clasificación de la Respuesta')),
                ('codigo', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*[a-zA-Z ]$', message='Este campo solo puede contener letras')], verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Clasificación de la Respuesta',
                'verbose_name_plural': 'Clasificaciones de las Respuestas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CodificadorAsunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Codificador de Asunto')),
                ('numero', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*[0-9]$', message='Este campo solo puede contener números')], verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Codificador de Asunto',
                'verbose_name_plural': 'Codificadores de Asuntos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Estado de la Queja')),
            ],
            options={
                'verbose_name': 'Estado de la Queja',
                'verbose_name_plural': 'Estados de las Quejas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Procedencia')),
                ('enviar', models.BooleanField(help_text='Indica si se enviará la respuesta de la queja')),
            ],
            options={
                'verbose_name': 'Procedencia',
                'verbose_name_plural': 'Procedencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoProcedencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Tipo de Procedencia')),
                ('cant_dias', models.IntegerField(default='0')),
            ],
            options={
                'verbose_name': 'Tipo de Procedencia',
                'verbose_name_plural': 'Tipos de Procedencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoQueja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Tipo de Queja')),
                ('numero', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*[a-zA-Z ]$', message='Este campo solo puede contener letras')], verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Tipo de Queja',
                'verbose_name_plural': 'Tipos de las Quejas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='calle',
            name='nombre',
            field=models.CharField(help_text='Nombre de la calle', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Nombre'),
        ),
    ]
