# Generated by Django 2.2.3 on 2019-12-18 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0002_auto_20210105_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedencia',
            name='enviar',
            field=models.BooleanField(default=True, help_text='Marque para enviar la respuesta por correo electrónico', verbose_name='Enviar Respuesta'),
        ),
        migrations.AlterField(
            model_name='tipoqueja',
            name='numero',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*[a-zA-Z ]$', message='Este campo solo puede contener letras')], verbose_name='Código'),
        ),
    ]
