# Generated by Django 2.2.3 on 2019-12-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0003_auto_20191218_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoprocedencia',
            name='cant_dias',
            field=models.PositiveSmallIntegerField(verbose_name='Días para Respuesta'),
        ),
    ]
