# Generated by Django 2.2 on 2020-01-19 04:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dpv_nomencladores', '0006_auto_20200117_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedencia',
            name='id_objecto',
            field=models.PositiveIntegerField(null=True, verbose_name='related object'),
        ),
        migrations.AddField(
            model_name='procedencia',
            name='tipo_contenido',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'dpv_nomencladores'), ('model', 'organismo')), models.Q(('app_label', 'dpv_nomencladores'), ('model', 'organizacion')), models.Q(('app_label', 'dpv_persona'), ('model', 'personanatural')), models.Q(('app_label', 'dpv_persona'), ('model', 'personajuridica')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Contenido de Procedencia'),
        ),
        migrations.AlterField(
            model_name='areatrabajo',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Área de Trabajo'),
        ),
        migrations.AlterField(
            model_name='areatrabajo',
            name='numero',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]*[0-9]$', message='Este campo solo puede contener números')], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='calle',
            name='nombre',
            field=models.CharField(help_text='Nombre de la calle', max_length=50, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='nombre',
            field=models.CharField(help_text='Nombre de la unidad.', max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Centro de trabajo'),
        ),
        migrations.AlterField(
            model_name='clasificacionrespuesta',
            name='codigo',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*[a-zA-Z ]$', message='Este campo solo puede contener letras')], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='clasificacionrespuesta',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Clasificación de la Respuesta'),
        ),
        migrations.AlterField(
            model_name='codificadorasunto',
            name='nombre',
            field=models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Codificador de Asunto'),
        ),
        migrations.AlterField(
            model_name='codificadorasunto',
            name='numero',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[0-9]*[0-9]$', message='Este campo solo puede contener números')], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='consejopopular',
            name='nombre',
            field=models.CharField(help_text='Nombre del consejo popular', max_length=30, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Consejo Popular'),
        ),
        migrations.AlterField(
            model_name='consejopopular',
            name='numero',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]*[0-9]$', message='Este campo solo puede contener números')], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='nombre',
            field=models.CharField(help_text='Identificador del destino', max_length=50, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Estado de la Queja'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=9, validators=[django.core.validators.MaxLengthValidator(9), django.core.validators.RegexValidator('^[a-zA-Z ]*[a-zA-Z ]$', message='Este campo solo puede contener letras')], verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='sigla',
            field=models.CharField(max_length=1, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1), django.core.validators.RegexValidator('^[a-zA-Z ]*[a-zA-Z ]$', message='Este campo solo puede contener letras')], verbose_name='Inicial'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(help_text='Nombre del municipio', max_length=30, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='numero',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]*[0-9]$', message='Este campo solo puede contener números')], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='nombre',
            field=models.CharField(help_text='Nombre del organismo.', max_length=50, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name=' Organismo'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='siglas',
            field=models.CharField(help_text='Siglas representativas del organismo', max_length=7, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")]),
        ),
        migrations.AlterField(
            model_name='piso',
            name='nombre',
            field=models.CharField(help_text='Nombre del piso', max_length=20, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='procedencia',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(help_text='Nombre del municipio', max_length=30, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='numero',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]*[0-9]$', message='Este campo solo puede contener números')], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='tipoprocedencia',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Tipo de Procedencia'),
        ),
        migrations.AlterField(
            model_name='tipoqueja',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Tipo de Queja'),
        ),
        migrations.AlterField(
            model_name='tipoqueja',
            name='numero',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*[a-zA-Z ]$', message='Este campo solo puede contener letras')], verbose_name='Código'),
        ),
        migrations.AlterUniqueTogether(
            name='areatrabajo',
            unique_together={('nombre', 'deleted_at'), ('numero', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='calle',
            unique_together={('nombre', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='centrotrabajo',
            unique_together={('nombre', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='clasificacionrespuesta',
            unique_together={('nombre', 'deleted_at'), ('codigo', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='codificadorasunto',
            unique_together={('nombre', 'deleted_at'), ('numero', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='concepto',
            unique_together={('nombre', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='consejopopular',
            unique_together={('nombre', 'deleted_at'), ('numero', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='destino',
            unique_together={('nombre', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='estado',
            unique_together={('nombre', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='genero',
            unique_together={('nombre', 'deleted_at'), ('sigla', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('nombre', 'deleted_at'), ('numero', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='organismo',
            unique_together={('nombre', 'deleted_at'), ('siglas', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='piso',
            unique_together={('nombre', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='procedencia',
            unique_together={('nombre', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='provincia',
            unique_together={('nombre', 'deleted_at'), ('numero', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='tipoprocedencia',
            unique_together={('nombre', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='tipoqueja',
            unique_together={('nombre', 'deleted_at'), ('numero', 'deleted_at')},
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'deleted_at')},
            },
        ),
    ]
