# Generated by Django 2.2.2 on 2020-02-05 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0010_conclusioncaso'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaAQueja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Respuesta a')),
            ],
            options={
                'verbose_name': 'Respuesta a',
                'verbose_name_plural': 'Respuestas a',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'deleted_at')},
            },
        ),
    ]
