# Generated by Django 2.2 on 2020-02-06 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0011_respuestaaqueja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedencia',
            name='enviar',
        ),
        migrations.AddField(
            model_name='tipoprocedencia',
            name='enviar',
            field=models.BooleanField(default=True, help_text='Marque para enviar la respuesta por correo electrónico', verbose_name='Enviar Respuesta'),
        ),
        migrations.AlterField(
            model_name='respuestaaqueja',
            name='nombre',
            field=models.CharField(help_text='A quien se le debe enviar o notificar la respuesta.', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Respuesta a'),
        ),
    ]
