# Generated by Django 2.2 on 2020-02-11 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0012_auto_20200206_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrotrabajo',
            name='nombre',
            field=models.CharField(help_text='Nombre de la unidad.', max_length=100, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Centro de trabajo'),
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='numero',
            field=models.CharField(blank=True, help_text='Número de la unidad', max_length=3, validators=[django.core.validators.RegexValidator('^[0-9]*[0-9]$', message='Este campo solo puede contener números'), django.core.validators.MaxLengthValidator(3)], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='siglas',
            field=models.CharField(help_text='Siglas de la entidad.', max_length=7, validators=[django.core.validators.MaxLengthValidator(7), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Siglas'),
        ),
    ]
