# Generated by Django 2.2 on 2020-02-11 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0013_auto_20200211_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabajo',
            name='nombre',
            field=models.CharField(max_length=90, validators=[django.core.validators.MaxLengthValidator(90), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Área de Trabajo'),
        ),
        migrations.AlterField(
            model_name='calle',
            name='nombre',
            field=models.CharField(help_text='Nombre de la calle', max_length=90, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', "), django.core.validators.MaxLengthValidator(90)], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clasificacionrespuesta',
            name='nombre',
            field=models.CharField(max_length=90, validators=[django.core.validators.MaxLengthValidator(90), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Clasificación de la Respuesta'),
        ),
        migrations.AlterField(
            model_name='codificadorasunto',
            name='nombre',
            field=models.CharField(max_length=250, validators=[django.core.validators.MaxLengthValidator(250), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Codificador de Asunto'),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='nombre',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='conclusioncaso',
            name='nombre',
            field=models.CharField(max_length=90, validators=[django.core.validators.MaxLengthValidator(90), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Conclusión del Caso'),
        ),
        migrations.AlterField(
            model_name='consejopopular',
            name='nombre',
            field=models.CharField(help_text='Nombre del consejo popular', max_length=90, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', "), django.core.validators.MaxLengthValidator(90)], verbose_name='Consejo Popular'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='nombre',
            field=models.CharField(help_text='Identificador del destino', max_length=90, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', "), django.core.validators.MaxLengthValidator(90)], verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255), django.core.validators.EmailValidator()], verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=90, validators=[django.core.validators.MaxLengthValidator(90), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Estado de la Queja'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=11, validators=[django.core.validators.MaxLengthValidator(11), django.core.validators.RegexValidator('^[a-zA-Z ]*[a-zA-Z ]$', message='Este campo solo puede contener letras')], verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='gobierno',
            name='nombre',
            field=models.CharField(max_length=90, validators=[django.core.validators.MaxLengthValidator(90), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Gobierno'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(help_text='Nombre del municipio', max_length=90, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', "), django.core.validators.MaxLengthValidator(90)], verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='nombre',
            field=models.CharField(help_text='Nombre del organismo.', max_length=90, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', "), django.core.validators.MaxLengthValidator(90)], verbose_name=' Organismo'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='nombre',
            field=models.CharField(max_length=90, validators=[django.core.validators.MaxLengthValidator(90), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='prensaescrita',
            name='nombre',
            field=models.CharField(max_length=90, validators=[django.core.validators.MaxLengthValidator(90), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Prensa Escrita'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(help_text='Nombre del municipio', max_length=30, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', "), django.core.validators.MaxLengthValidator(30)], verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='numero',
            field=models.CharField(max_length=11, validators=[django.core.validators.MaxLengthValidator(11), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='tipoprocedencia',
            name='nombre',
            field=models.CharField(max_length=90, validators=[django.core.validators.MaxLengthValidator(90), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Tipo de Procedencia'),
        ),
    ]
