# Generated by Django 2.2.2 on 2020-05-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0015_auto_20200211_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anónimo', max_length=8, verbose_name='Anónimo')),
            ],
            options={
                'verbose_name': 'Anónimo',
                'verbose_name_plural': 'Anónimos',
            },
        ),
    ]
