# Generated by Django 2.2.2 on 2020-07-19 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0018_auto_20200719_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrotrabajo',
            name='siglas',
            field=models.CharField(help_text='Siglas de la entidad.', max_length=15, validators=[django.core.validators.MaxLengthValidator(7), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='siglas',
            field=models.CharField(help_text='Siglas representativas del organismo', max_length=15, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")]),
        ),
        migrations.AlterField(
            model_name='prensaescrita',
            name='siglas',
            field=models.CharField(max_length=15, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Siglas'),
        ),
    ]
