# Generated by Django 2.2.2 on 2020-07-25 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0019_auto_20200719_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoqueja',
            name='numero',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('[0-9 ,.:;!@#$%^&*()_+-={}[]\\|~`]', message='Este campo no puede contener letras')], verbose_name='Código'),
        ),
    ]
