# Generated by Django 2.2.2 on 2020-07-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0020_auto_20200725_1924'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='centrotrabajo',
            unique_together={('numero', 'deleted_at'), ('nombre', 'deleted_at')},
        ),
    ]
