# Generated by Django 2.2.2 on 2020-07-27 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0022_auto_20200727_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado')),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre de la red social', max_length=25, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(25)], verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
