# Generated by Django 2.2.2 on 2020-07-27 01:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0023_redsocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedenciaWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado')),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre de la persona o Perfil', max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(200), django.core.validators.RegexValidator('^[a-zA-ZñáéíóúÁÉÍÓÚÑ ]*[a-zA-ZñáéíóúÁÉÍÓÚÑ ]$', message='Este campo solo puede contener letras')], verbose_name='Nombre')),
                ('perfil', models.CharField(blank=True, default='', help_text='Idetntificador del perfil social', max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(200), django.core.validators.RegexValidator('^[a-zA-ZñáéíóúÁÉÍÓÚÑ ]*[a-zA-ZñáéíóúÁÉÍÓÚÑ ]$', message='Este campo solo puede contener letras')], verbose_name='Perfil Social')),
                ('email', models.EmailField(blank=True, default='', help_text='Correo eletrónico del perfil', max_length=254, verbose_name='Correo Electrónico')),
                ('red_social', models.ForeignKey(blank=True, default='', help_text='Red social a la que pertenece el perfil.', on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.RedSocial', verbose_name='Red Social')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
