# Generated by Django 2.2.2 on 2020-07-27 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0024_procedenciaweb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedenciaweb',
            options={'ordering': ['nombre'], 'verbose_name': 'Red Social', 'verbose_name_plural': 'Redes Sociales'},
        ),
        migrations.AlterModelOptions(
            name='redsocial',
            options={'ordering': ['nombre'], 'verbose_name': 'Red Social', 'verbose_name_plural': 'Redes Sociales'},
        ),
        migrations.AlterUniqueTogether(
            name='procedenciaweb',
            unique_together={('perfil', 'email', 'red_social', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='redsocial',
            unique_together={('nombre', 'deleted_at')},
        ),
    ]
