# Generated by Django 2.2.2 on 2020-07-27 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0025_auto_20200727_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedencia',
            name='tipo_contenido',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'dpv_nomencladores'), ('model', 'organismo')), models.Q(('app_label', 'dpv_nomencladores'), ('model', 'organizacion')), models.Q(('app_label', 'dpv_nomencladores'), ('model', 'prensaescrita')), models.Q(('app_label', 'dpv_nomencladores'), ('model', 'telefono')), models.Q(('app_label', 'dpv_nomencladores'), ('model', 'email')), models.Q(('app_label', 'dpv_nomencladores'), ('model', 'gobierno')), models.Q(('app_label', 'dpv_nomencladores'), ('model', 'procedenciaweb')), models.Q(('app_label', 'dpv_persona'), ('model', 'personanatural')), models.Q(('app_label', 'dpv_persona'), ('model', 'personajuridica')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Contenido de Procedencia'),
        ),
    ]
