# Generated by Django 2.2.2 on 2020-08-21 08:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0027_redsocial_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gobierno',
        ),
        migrations.AddField(
            model_name='organizacion',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Correo eletrónico de contacto de la prensa', max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='nombre_contacto',
            field=models.CharField(blank=True, default='', help_text='Nombre de la persona de contacto de la organización', max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(200), django.core.validators.RegexValidator('^[a-zA-ZñáéíóúÁÉÍÓÚÑ ]*[a-zA-ZñáéíóúÁÉÍÓÚÑ ]$', message='Este campo solo puede contener letras')], verbose_name='Nombre de contacto'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='siglas',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Siglas'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='telefono',
            field=models.CharField(blank=True, default='', help_text='Teléfono de contacto de la organización', max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8), django.core.validators.RegexValidator('^[0-9]*[0-9]$', message='Este campo solo puede contener números')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='procedencia',
            name='tipo_contenido',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'dpv_nomencladores'), ('model', 'organismo')), models.Q(('app_label', 'dpv_nomencladores'), ('model', 'organizacion')), models.Q(('app_label', 'dpv_nomencladores'), ('model', 'prensaescrita')), models.Q(('app_label', 'dpv_nomencladores'), ('model', 'telefono')), models.Q(('app_label', 'dpv_nomencladores'), ('model', 'email')), models.Q(('app_label', 'dpv_nomencladores'), ('model', 'procedenciaweb')), models.Q(('app_label', 'dpv_persona'), ('model', 'personanatural')), models.Q(('app_label', 'dpv_persona'), ('model', 'personajuridica')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Contenido de Procedencia'),
        ),
    ]
