# Generated by Django 2.2.2 on 2020-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0029_auto_20200821_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='nombre_contacto',
            field=models.CharField(blank=True, default='', help_text='Nombre de la persona que contacto por email', max_length=220, verbose_name='Nombre de contacto'),
        ),
    ]
