# Generated by Django 2.2.2 on 2020-09-12 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0031_telefono_nombre_contacto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('email', 'nombre_contacto', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='telefono',
            unique_together={('numero', 'nombre_contacto', 'deleted_at')},
        ),
    ]
