# Generated by Django 2.2.2 on 2021-02-01 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0034_redsocial_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelSolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado')),
                ('nombre', models.CharField(max_length=90, validators=[django.core.validators.MaxLengthValidator(90), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Nivel de Solución')),
                ('codigo', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[a-zA-ZñáéíóúÁÉÍÓÚÑ ]*[a-zA-ZñáéíóúÁÉÍÓÚÑ ]$', message='Este campo solo puede contener letras')], verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Nivel de Solución',
                'verbose_name_plural': 'Niveles de Solución',
                'ordering': ['nombre'],
                'unique_together': {('codigo', 'deleted_at'), ('nombre', 'deleted_at')},
            },
        ),
    ]
