# Generated by Django 2.2 on 2020-01-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignaQuejaDpto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Asignación')),
            ],
            options={
                'verbose_name': 'Queja asignada a Depto',
                'verbose_name_plural': 'Quejas asignadas a Depto',
            },
        ),
        migrations.CreateModel(
            name='AsignaQuejaTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Asignación')),
            ],
            options={
                'verbose_name': 'Queja asignada a Técnico',
                'verbose_name_plural': 'Quejas asignadas a Técnico',
            },
        ),
        migrations.CreateModel(
            name='Damnificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Damnificado',
                'verbose_name_plural': 'Damnificados',
            },
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_num', models.CharField(max_length=15, verbose_name='Dirección Número')),
                ('numero', models.CharField(max_length=10, verbose_name='Número Queja')),
                ('referencia', models.CharField(blank=True, default='', max_length=50, verbose_name='Referencia')),
                ('fecha_radicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Radicación')),
                ('texto', models.TextField(max_length=1000, verbose_name='Cuerpo de la queja')),
            ],
            options={
                'verbose_name': 'Queja',
                'verbose_name_plural': 'Quejas',
            },
        ),
        migrations.CreateModel(
            name='QuejaRechazada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(default='Motivo por defecto', help_text='Motivo por el cual se rechaza la queja', verbose_name='Motivo de Rechazo')),
            ],
            options={
                'verbose_name': 'Queja Rechazada',
                'verbose_name_plural': 'Quejas Rechazadas',
            },
        ),
        migrations.CreateModel(
            name='QuejaRedirigida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(default='Motivo por defecto', help_text='Motivo por el cual se rechaza la queja', verbose_name='Motivo de Rechazo')),
            ],
        ),
    ]
