# Generated by Django 2.2 on 2020-01-17 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpv_persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dpv_nomencladores', '0005_auto_20200111_0037'),
        ('dpv_respuesta', '0001_initial'),
        ('dpv_quejas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaQueja',
            fields=[
                ('respuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpv_respuesta.Respuesta')),
                ('queja', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='dpv_quejas.Queja')),
            ],
            bases=('dpv_respuesta.respuesta',),
        ),
        migrations.AddField(
            model_name='quejaredirigida',
            name='queja',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirigida', to='dpv_quejas.Queja'),
        ),
        migrations.AddField(
            model_name='quejaredirigida',
            name='redirigida_por',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Rechazada Por'),
        ),
        migrations.AddField(
            model_name='quejarechazada',
            name='queja',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rechazada', to='dpv_quejas.Queja'),
        ),
        migrations.AddField(
            model_name='quejarechazada',
            name='rechazada_por',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Rechazada Por'),
        ),
        migrations.AddField(
            model_name='queja',
            name='asunto',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.CodificadorAsunto', verbose_name='Asunto Queja'),
        ),
        migrations.AddField(
            model_name='queja',
            name='clasificacion',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.TipoQueja', verbose_name='Tipo de Queja'),
        ),
        migrations.AddField(
            model_name='queja',
            name='dir_calle',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='queja_calle', to='dpv_nomencladores.Calle', verbose_name='Dirección Calle'),
        ),
        migrations.AddField(
            model_name='queja',
            name='dir_cpopular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.ConsejoPopular', verbose_name='Dirección Consejo Popular'),
        ),
        migrations.AddField(
            model_name='queja',
            name='dir_entrecalle1',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='queja_entrecalle1', to='dpv_nomencladores.Calle', verbose_name='Dirección Primera Entrecalle'),
        ),
        migrations.AddField(
            model_name='queja',
            name='dir_entrecalle2',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='queja_entrecalle2', to='dpv_nomencladores.Calle', verbose_name='Dirección Segunda Entrecalle'),
        ),
        migrations.AddField(
            model_name='queja',
            name='dir_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.Municipio', verbose_name='Dirección Municipio'),
        ),
        migrations.AddField(
            model_name='queja',
            name='estado',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.Estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='queja',
            name='procedencia',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodencia', to='dpv_nomencladores.Procedencia'),
        ),
        migrations.AddField(
            model_name='damnificado',
            name='queja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damnificado', to='dpv_quejas.Queja'),
        ),
        migrations.AddField(
            model_name='asignaquejatecnico',
            name='quejatecnico',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quejatecnico', to='dpv_quejas.Queja'),
        ),
        migrations.AddField(
            model_name='asignaquejatecnico',
            name='tecnico',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnico', to='dpv_respuesta.Tecnico'),
        ),
        migrations.AddField(
            model_name='asignaquejadpto',
            name='dpto',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dpto', to='dpv_nomencladores.AreaTrabajo'),
        ),
        migrations.AddField(
            model_name='asignaquejadpto',
            name='quejadpto',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quejadpto', to='dpv_quejas.Queja'),
        ),
        migrations.CreateModel(
            name='DamnificadoNatural',
            fields=[
                ('damnificado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpv_quejas.Damnificado')),
                ('persona_natural', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_natural', to='dpv_persona.PersonaNatural')),
            ],
            bases=('dpv_quejas.damnificado',),
        ),
        migrations.CreateModel(
            name='DamnificadoJuridico',
            fields=[
                ('damnificado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpv_quejas.Damnificado')),
                ('persona_juridica', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_juridica', to='dpv_persona.PersonaJuridica')),
            ],
            bases=('dpv_quejas.damnificado',),
        ),
    ]
