# Generated by Django 2.2 on 2020-01-17 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_quejas', '0002_auto_20200117_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaquejadpto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignaquejadpto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='asignaquejadpto',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='asignaquejatecnico',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignaquejatecnico',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='asignaquejatecnico',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='damnificado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='damnificado',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='damnificado',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='queja',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queja',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='queja',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='quejarechazada',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quejarechazada',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='quejarechazada',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='quejaredirigida',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quejaredirigida',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='quejaredirigida',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
    ]
