# Generated by Django 2.2 on 2020-01-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_quejas', '0005_quejanotificada_notificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='tiempo',
            field=models.PositiveSmallIntegerField(default=0, help_text='Tiempo en días que tiene de radicada la queja', verbose_name='Tiempo en proceso'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='texto',
            field=models.TextField(max_length=3000, verbose_name='Cuerpo de la queja'),
        ),
    ]
