# Generated by Django 2.2.2 on 2020-01-27 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dpv_quejas', '0007_auto_20200124_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queja',
            name='clasificacion',
        ),
        migrations.AddField(
            model_name='queja',
            name='asunto_texto',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Asunto'),
        ),
        migrations.AddField(
            model_name='queja',
            name='no_procendencia',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='No. de Procedencia'),
        ),
        migrations.AddField(
            model_name='queja',
            name='no_radicacion',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='No. Radicación'),
        ),
        migrations.AddField(
            model_name='queja',
            name='radicado_por',
            field=models.ForeignKey(blank='', default='', on_delete=django.db.models.deletion.CASCADE, related_name='quejas_radicadas', to=settings.AUTH_USER_MODEL, verbose_name='Radicada Por'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='asunto',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.CodificadorAsunto', verbose_name='Asunto Código'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='numero',
            field=models.CharField(max_length=14, verbose_name='Número Queja'),
        ),
    ]
