# Generated by Django 2.2.2 on 2020-03-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_quejas', '0011_auto_20200320_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaqueja',
            name='gestion',
            field=models.TextField(blank=True, default='', help_text='Gestion realizada por parte del tecnico para dar respuesta a la queja', verbose_name='Gestion realizada'),
        ),
    ]
