# Generated by Django 2.2.2 on 2020-03-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_quejas', '0012_respuestaqueja_gestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestaqueja',
            options={'verbose_name': 'Respuesta a Queja', 'verbose_name_plural': 'Respuestas a Quejas'},
        ),
    ]
