# Generated by Django 2.2.2 on 2020-08-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_quejas', '0013_auto_20200327_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='procedencia',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='dpv_nomencladores.Procedencia'),
        ),
    ]
