# Generated by Django 2.2.2 on 2021-02-01 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dpv_quejas', '0014_auto_20200821_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaquejadpto',
            name='asignador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
