# Generated by Django 2.2.2 on 2021-02-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0035_nivelsolucion'),
        ('dpv_quejas', '0016_asignaquejatecnico_asignador'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaqueja',
            name='conclusion_caso',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.ConclusionCaso', verbose_name='Conclusión del Caso'),
        ),
        migrations.AddField(
            model_name='respuestaqueja',
            name='nivel_solucion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.NivelSolucion', verbose_name='Nivel de la Solución'),
        ),
    ]
