# Generated by Django 2.2.2 on 2021-02-05 05:56

import apps.dpv_quejas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_quejas', '0017_auto_20210201_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, upload_to=apps.dpv_quejas.models.scramble_upload_document, verbose_name='Copia digital'),
        ),
    ]
