# Generated by Django 2.2.2 on 2021-02-05 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_quejas', '0018_queja_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damnificado',
            name='queja',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damnificado', to='dpv_quejas.Queja'),
        ),
    ]
