# Generated by Django 2.2.2 on 2021-02-15 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_quejas', '0019_auto_20210205_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damnificado',
            name='queja',
        ),
        migrations.AddField(
            model_name='queja',
            name='damnificado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dpv_quejas.Damnificado'),
        ),
    ]
