# Generated by Django 2.2.2 on 2021-02-03 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Eliminado')),
                ('main_text', models.TextField(blank=True, default='', null=True, verbose_name='Texto')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de la notificación')),
                ('level', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('readed', models.BooleanField(default=False, verbose_name='Visto')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario notificado')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ('-date_time', 'user'),
            },
        ),
    ]
