# Generated by Django 2.2 on 2020-02-02 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_persona', '0004_auto_20200201_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajuridica',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
