# Generated by Django 2.2.2 on 2020-03-10 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_persona', '0005_auto_20200202_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajuridica',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='movil',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8), django.core.validators.RegexValidator('^[0-9]*[0-9]$', message='Este campo solo puede contener números')], verbose_name='Teléfono Movil'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8), django.core.validators.RegexValidator('^[0-9]*[0-9]$', message='Este campo solo puede contener números')], verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='movil',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8), django.core.validators.RegexValidator('^[0-9]*[0-9]$', message='Este campo solo puede contener números')], verbose_name='Teléfono Movil'),
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8), django.core.validators.RegexValidator('^[0-9]*[0-9]$', message='Este campo solo puede contener números')], verbose_name='Teléfono Fijo'),
        ),
    ]
