# Generated by Django 2.2.2 on 2020-07-19 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_persona', '0006_auto_20200310_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajuridica',
            name='sigla',
            field=models.CharField(blank=True, help_text='Siglas identificativas de la entidad.', max_length=15, verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='apellidos',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('^[a-zA-ZñáéíóúÁÉÍÓÚÑ ]*[a-zA-ZñáéíóúÁÉÍÓÚÑ ]$', message='Este campo solo puede contener letras')]),
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='nombre',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30), django.core.validators.RegexValidator('^[a-zA-ZñáéíóúÁÉÍÓÚÑ ]*[a-zA-ZñáéíóúÁÉÍÓÚÑ ]$', message='Este campo solo puede contener letras')]),
        ),
    ]
