# Generated by Django 2.2.2 on 2020-09-12 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_persona', '0007_auto_20200719_1646'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personajuridica',
            unique_together={('codigo_nit', 'deleted_at'), ('codigo_reuup', 'deleted_at'), ('nombre', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='personanatural',
            unique_together={('ci', 'deleted_at')},
        ),
    ]
