# Generated by Django 2.2.2 on 2021-02-15 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_persona', '0008_auto_20200912_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajuridica',
            name='cpopular',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.ConsejoPopular', verbose_name='Consejo Popular'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.Municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='cpopular',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.ConsejoPopular', verbose_name='Consejo Popular'),
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.Municipio', verbose_name='Municipio'),
        ),
    ]
